import json
import os
from collections.abc import AsyncIterator
from typing import Any

from openai import AsyncOpenAI

from AgentBI.src.agents.email_agent import EmailAgent
from AgentBI.src.agents.assistant_registry import DEFAULT_ASSISTANT_CAPABILITIES, DEFAULT_ASSISTANT_PROMPT, capability_prompt
from AgentBI.src.repositories.sqlite_chat_repository import SqliteChatRepository


class ChatAgent:
    system_prompt = (
        "你是 AgentBI 工作台助手。回答应清晰、直接。"
        "需要发送邮件时调用 delegate_email；邮件子代理会查询 users 中的 username/email，"
        "再根据查询结果撰写并发送邮件。不要自行发送邮件。"
    )
    def __init__(
        self,
        system_prompt: str | None = None,
        capability_ids: list[str] | None = None,
        include_runtime_context: bool = True,
        repository: SqliteChatRepository | None = None,
    ):
        self.system_prompt = system_prompt or DEFAULT_ASSISTANT_PROMPT
        self.capability_ids = capability_ids if capability_ids is not None else DEFAULT_ASSISTANT_CAPABILITIES
        self.include_runtime_context = include_runtime_context
        self.repository = repository

    runtime_context_instruction = (
        "The latest user message may include a runtime_context block generated by the application. "
        "Treat it as current runtime facts and do not quote the wrapper in the response."
    )

    @staticmethod
    def client_headers() -> dict[str, str]:
        return {
            "User-Agent": os.getenv(
                "LLM_USER_AGENT",
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36",
            )
        }

    @staticmethod
    def tool_definitions(capability_ids: list[str] | None = None) -> list[dict[str, Any]]:
        if "agent.email" not in (capability_ids if capability_ids is not None else DEFAULT_ASSISTANT_CAPABILITIES):
            return []
        return [
            {
                "type": "function",
                "function": {
                    "name": "delegate_email",
                    "description": "将邮件撰写、收件人查询和发送委派给邮件子代理。",
                    "parameters": {
                        "type": "object",
                        "properties": {"instruction": {"type": "string", "description": "邮件发送任务说明"}},
                        "required": ["instruction"],
                    },
                },
            },
        ]

    async def stream(
        self,
        messages: list[dict[str, str]],
        provider: dict[str, Any],
        model: str,
        temperature: float,
        runtime_context: dict[str, str] | None = None,
    ) -> AsyncIterator[dict[str, Any]]:
        client = AsyncOpenAI(
            api_key=provider["api_key"],
            base_url=provider["base_url"],
            default_headers=self.client_headers(),
        )
        request_messages = self.build_request_messages(messages, runtime_context or {})
        async for event in self._stream_tool_loop(client, request_messages, model, temperature):
            yield event

    def build_request_messages(
        self,
        messages: list[dict[str, Any]],
        runtime_context: dict[str, str],
    ) -> list[dict[str, Any]]:
        system_parts = [self.system_prompt, capability_prompt(self.capability_ids)]
        if self.include_runtime_context:
            system_parts.append(self.runtime_context_instruction)
        return [
            {"role": "system", "content": "\n".join(filter(None, system_parts))},
            *(self.with_runtime_context(messages, runtime_context) if self.include_runtime_context else messages),
        ]

    async def _stream_tool_loop(
        self,
        client: AsyncOpenAI,
        messages: list[dict[str, Any]],
        model: str,
        temperature: float,
    ) -> AsyncIterator[dict[str, Any]]:
        for _ in range(4):
            content_parts: list[str] = []
            tool_calls: dict[int, dict[str, str]] = {}
            request: dict[str, Any] = {"model": model, "messages": messages, "temperature": temperature, "stream": True}
            if tools := self.tool_definitions(self.capability_ids):
                request["tools"] = tools
            response = await client.chat.completions.create(**request)
            async for chunk in response:
                choice = chunk.choices[0] if chunk.choices else None
                if not choice:
                    continue
                delta = choice.delta
                if delta.content:
                    content_parts.append(delta.content)
                    yield {"type": "delta", "content": delta.content}
                reasoning = getattr(delta, "reasoning_content", None)
                if reasoning:
                    yield {"type": "reasoning_summary", "content": reasoning}
                for tool_call in delta.tool_calls or []:
                    entry = tool_calls.setdefault(tool_call.index, {"id": "", "name": "", "arguments": ""})
                    if tool_call.id:
                        entry["id"] = tool_call.id
                    if tool_call.function and tool_call.function.name:
                        entry["name"] = tool_call.function.name
                    if tool_call.function and tool_call.function.arguments:
                        entry["arguments"] += tool_call.function.arguments

            if not tool_calls:
                return
            messages.append(self._assistant_tool_message(content_parts, tool_calls))
            for call in tool_calls.values():
                if call["name"] == "delegate_email":
                    yield {"type": "tool_started", "tool": "邮件子代理"}
                    async for event in EmailAgent(self.repository).stream(
                        client,
                        model,
                        temperature,
                        self._email_instruction(messages, call["arguments"]),
                    ):
                        yield event
                    yield {"type": "tool_finished", "tool": "邮件子代理", "content": "邮件任务已由子代理处理"}
                    return

                yield {"type": "tool_finished", "tool": call["name"], "content": "主代理不执行该工具"}
                return

    @staticmethod
    def with_runtime_context(messages: list[dict[str, Any]], runtime: dict[str, str]) -> list[dict[str, Any]]:
        wrapped = [dict(message) for message in messages]
        for index in range(len(wrapped) - 1, -1, -1):
            message = wrapped[index]
            if message.get("role") != "user" or not isinstance(message.get("content"), str):
                continue
            metadata = "\n".join([
                f"current_time: {runtime.get('current_time', '')}",
                f"timezone: {runtime.get('timezone', 'Asia/Shanghai')}",
                f"locale: {runtime.get('locale', 'zh-CN')}",
                f"user_name: {runtime.get('user_name', '用户')}",
            ])
            message["content"] = f"<runtime_context>\n{metadata}\n</runtime_context>\n\n<user_request>\n{message['content']}\n</user_request>"
            return wrapped
        return wrapped

    @staticmethod
    def _assistant_tool_message(content_parts: list[str], tool_calls: dict[int, dict[str, str]]) -> dict[str, Any]:
        return {
            "role": "assistant",
            "content": "".join(content_parts) or None,
            "tool_calls": [{
                "id": call["id"],
                "type": "function",
                "function": {"name": call["name"], "arguments": call["arguments"]},
            } for call in tool_calls.values()],
        }

    @staticmethod
    def _email_instruction(messages: list[dict[str, Any]], arguments: str) -> str:
        try:
            instruction = json.loads(arguments or "{}").get("instruction", "发送邮件")
        except json.JSONDecodeError:
            instruction = arguments or "发送邮件"
        user_request = next((item["content"] for item in reversed(messages) if item.get("role") == "user"), "")
        tool_results = [str(item["content"]) for item in messages if item.get("role") == "tool"]
        context = "\n".join(tool_results) or "无额外查询结果。"
        return f"用户原始请求：{user_request}\n邮件任务：{instruction}\n主代理查询结果：{context}"
