import re
import secrets
from collections.abc import Callable
from typing import Any

from AgentBI.src.repositories.sqlite_chat_repository import SqliteChatRepository
from AgentBI.src.tools.send_email_tool import send_email_message

EMAIL_RE = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")


def build_login_code_content(code: str) -> tuple[str, str]:
    plain = (
        "AgentBI 登录验证\n\n"
        f"你的登录验证码是：{code}\n\n"
        "验证码将在 5 分钟后失效。为了保护你的账户，请勿将验证码转发给其他人。\n"
        "如果不是你本人操作，可以忽略这封邮件。"
    )
    html = f"""<!doctype html>
<html lang="zh-CN">
  <body style="margin:0;background:#efede6;color:#171717;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Microsoft YaHei',sans-serif;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#efede6;padding:36px 16px;">
      <tr><td align="center">
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:560px;background:#171717;color:#efede6;border-collapse:collapse;">
          <tr><td style="padding:24px 28px;border-bottom:1px solid #3b3b38;">
            <span style="display:inline-block;width:12px;height:22px;background:#d9ff36;vertical-align:middle;margin-right:10px;"></span>
            <strong style="font-size:16px;letter-spacing:2px;vertical-align:middle;">AgentBI</strong>
            <span style="float:right;color:#77756f;font:11px monospace;letter-spacing:1px;">SECURE ACCESS / 01</span>
          </td></tr>
          <tr><td style="padding:42px 28px 26px;">
            <p style="margin:0 0 12px;color:#d9ff36;font:11px monospace;letter-spacing:2px;">LOGIN VERIFICATION</p>
            <h1 style="margin:0;font-size:30px;line-height:1.25;">确认是你，<br>然后继续工作。</h1>
            <p style="margin:22px 0 10px;color:#aaa79f;font-size:14px;line-height:1.7;">请在登录页面输入下面的验证码：</p>
            <div style="margin:0;padding:22px 18px;background:#d9ff36;color:#111;text-align:center;font:700 36px/1 monospace;letter-spacing:12px;">{code}</div>
            <p style="margin:16px 0 0;color:#aaa79f;font-size:13px;line-height:1.7;">验证码将在 <strong style="color:#efede6;">5 分钟</strong>后失效，请勿转发给其他人。</p>
          </td></tr>
          <tr><td style="padding:18px 28px 24px;border-top:1px solid #3b3b38;color:#77756f;font-size:12px;line-height:1.6;">
            如果不是你本人操作，可以忽略这封邮件。<br>
            <span style="color:#4f4f4a;">This message was generated by your local AgentBI workspace.</span>
          </td></tr>
        </table>
      </td></tr>
    </table>
  </body>
</html>"""
    return plain, html


class LoginService:
    """Deterministic local email-code login without model orchestration or Redis."""

    def __init__(
        self,
        repository: SqliteChatRepository,
        sender: Callable[[str, str, str], str] | None = None,
        code_factory: Callable[[], str] | None = None,
    ):
        self.repository = repository
        self.sender = sender or send_email_message
        self.supports_html = sender is None
        self.code_factory = code_factory or (lambda: f"{secrets.randbelow(1_000_000):06d}")

    def send_code(self, identity: str) -> dict[str, str]:
        identity = identity.strip()
        existing = self.repository.find_user(identity)
        target_email = existing["email"] if existing else identity.lower()
        if not EMAIL_RE.fullmatch(target_email):
            raise ValueError("请输入已注册的用户名，或使用有效邮箱首次登录")
        code = self.code_factory()
        self.repository.create_login_code(identity, code, target_email)
        plain, html = build_login_code_content(code)
        if self.supports_html:
            send_email_message(target_email, "AgentBI 登录验证码", plain, html_content=html)
        else:
            self.sender(target_email, "AgentBI 登录验证码", plain)
        return {"target_email": target_email}

    def login(self, identity: str, code: str) -> dict[str, Any] | None:
        record = self.repository.consume_login_code(identity.strip(), code.strip())
        if not record:
            return None
        return self.repository.find_user(record["target_email"]) or self.repository.create_user(record["target_email"])
